export const districts = [
	'Abraão',
	'Açores',
	'Agronômica',
	'Alto Ribeirão Leste',
	'Alto Ribeirão',
	'Armação',
	'Autódromo',
	'Balneário',
	'Barra da Lagoa',
	'Barra do Sambaqui',
	'Base Aérea',
	'Bom Abrigo',
	'Cachoeira do Bom Jesus Leste',
	'Cachoeira do Bom Jesus',
	'Cacupé',
	'Caiacanga',
	'Caieira',
	'Campeche Central',
	'Campeche Leste',
	'Campeche Norte',
	'Campeche Sul',
	'Canasvieiras',
	'Canto da Lagoa',
	'Canto do Lamim',
	'Canto dos Araçás',
	'Canto',
	'Capivari',
	'Capoeiras',
	'Carianos',
	'Centro',
	'Coloninha',
	'Coqueiros',
	'Córrego Grande',
	'Costeira do Pirajubaé',
	'Costeira do Ribeirão',
	'Daniela',
	'Dunas da Lagoa',
	'Estreito',
	'Forte',
	'Ingleses Centro',
	'Ingleses Norte',
	'Ingleses Sul',
	'Itacorubi',
	'Itaguaçu',
	'Jardim Atlântico',
	'João Paulo',
	'José Mendes',
	'Jurere Leste',
	'Jurere Oeste',
	'Lagoa Pequena',
	'Lagoa',
	'Lagoinha do Norte',
	'Moenda',
	'Monte Cristo',
	'Monte Verde',
	'Morro das Pedras',
	'Pantanal',
	'Pântano do Sul',
	'Pedregal',
	'Pedrita',
	'Ponta das Canas',
	'Porto da Lagoa',
	'Praia Brava',
	'Praia Mole',
	'Ratones',
	'Recanto dos Açores',
	'Ressacada',
	'Retiro',
	'Ribeirão da Ilha',
	'Rio Tavares Central',
	'Rio Tavares do Norte',
	'Saco dos Limões',
	'Saco Grande',
	'Sambaqui',
	'Santa Mônica',
	'Santinho',
	'Santo Antônio',
	'São João do Rio Vermelho',
	'Tapera da Base',
	'Tapera',
	'Trindade',
	'Vargem de Fora',
	'Vargem do Bom Jesus',
	'Vargem Grande',
	'Vargem Pequena',
];